networks:
  dev:
    driver: bridge

services:
  dashboard-app:
    image: docker.io/library/dashboardapp:v2
    depends_on:
      - "dashboard_db"
    container_name: dashboardapp-api
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__Default=User ID=postgres;Password=postgres;Server=dashboard_db;Port=5432;Database=DashboardDB;
      - ConnectionStrings__Identity=User ID=postgres;Password=postgres;Server=dashboard_db;Port=5432;Database=DashboardIdentityDB;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  dashboard_db:
    image: postgres:latest
    container_name: dashboard_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DashboardDB
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - dashboard_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  dashboard_data: